blogs/urls.py
from django.urls import path

from blogs.apps import BlogsConfig
from blogs.views import BlogCreateView, BlogListView, BlogDetailView, BlogDeleteView, BlogUpdateView

app_name = BlogsConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('list/', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='blog_detail_view'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    body = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blogs/', verbose_name='Превью', **NULLABLE)
    date_of_creation = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blogs/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from pytils.translit import slugify

from blogs.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'preview')
    success_url = reverse_lazy('blogs:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body', 'preview', 'is_published')
    success_url = reverse_lazy('blogs:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blogs:blog_detail_view', args=[self.kwargs.get('pk')])


class BlogDetailView(DetailView):
    model = Blog
    extra_context = {
        'title': 'SkyStore',
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogListView(ListView):
    model = Blog
    extra_context = {
        'title': 'Статьи'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blogs:blog_list')

blogs/templates/blogs/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Удаление блога
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>
                    Вы точно хотите удалить блог - {{object.title}}?
                </p>
                <button type="submit" class="btn btn-outline-danger">
                        Удалить
                </button>
                <a href="{% url 'blogs:blog_list' %}" class="btn btn-outline-warning">Отмена</a>

            </div>
        </div>
    </div>
</form>
{% endblock %}

blogs/templates/blogs/blog_detail.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h3 class="my-0 font-weight-normal">{{object.title}}</h3>
                    <h4 class="my-0 font-weight-normal">slug: {{object.slug}}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{object.body}}</li>
                    </ul>
                </div>
                <div class="card-footer">
                    Просмотры: {{ object.views_count }}
                </div>
            </div>
        </div>
        <div class="col-6">
            <img src="/media/{{ object.image }}" class="img-fluid" alt="Card image cap">
        </div>
    </div>
</div>

{% endblock %}

blogs/templates/blogs/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Редактирование блога
                {% else %}
                Добавление блога
                {% endif %}
            </div>
            <div class="card-body">

                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                        Сохранить
                    {% else %}
                        Добавить
                    {% endif %}
                </button>
                <a href="{% url 'blogs:blog_list' %}" class="btn btn-outline-warning">Отмена</a>

            </div>
        </div>
    </div>
</form>
{% endblock %}

blogs/templates/blogs/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<a href="{% url 'blogs:blog_create' %}" type="button"
   class="btn btn-lg btn-outline-primary mb-5">Добавить блог</a>
<div class="row text-center">
    {% for object in object_list %}
    <div class="card" style="width: 18rem;">
        <img src="/media/{{ object.image }}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{ object.title }}</h5>
            <p class="card-text">{{ object.body|truncatechars:100 }}</p>
            <a href="{% url 'blogs:blog_detail_view' object.pk %}" type="button"
               class="btn btn-lg btn-block btn-outline-primary mb-3">Посмотреть</a>
            <a href="{% url 'blogs:blog_update' object.pk  %}" type="button"
               class="btn btn-outline-warning float-left">Изменить</a>
            <a href="{% url 'blogs:blog_delete' object.pk  %}" type="button"
               class="btn btn-outline-danger float-right">Удалить</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}