blogs/urls.py
from django.urls import path

from blogs.apps import BlogsConfig
from blogs.views import BlogCreateView, BlogListView, BlogDetailView, BlogDeleteView, BlogUpdateView

app_name = BlogsConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('list/', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='blog_detail_view'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import contacts, CategoryCreateView, CategoryListView, ProductsListView, \
    CategoryUpdateView, CategoryDeleteView, ProductCreateView, ProductUpdateView, ProductDeleteView, ProductDetailView, \
    HomeView

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contacts/', contacts, name='contacts'),
    path('category/<int:pk>', ProductsListView.as_view(), name='category'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>', CategoryDeleteView.as_view(), name='category_delete'),
    path('category_list/', CategoryListView.as_view(), name='category_list'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('product/view/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_detail_view'),
    path('product/delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegistererView, verify_view, UserUpdateView, user_password_recovery

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('user_recovery/', user_password_recovery, name='user_password_recovery'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegistererView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('verify/<str:verify_key>', verify_view, name='verify'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Email')

    phone = models.CharField(max_length=30, verbose_name='Телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    country = models.CharField(max_length=100, verbose_name='Страна', **NULLABLE)
    verify_key = models.CharField(max_length=15, verbose_name='Ключ верификации', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from catalog.forms import StyleFormMixin
from users.models import User


class CreateUserForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random

from django.conf import settings
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView

from users.forms import CreateUserForm, UserForm
from users.models import User


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegistererView(CreateView):
    model = User
    form_class = CreateUserForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):
        new_user = form.save()
        verify_key = ''.join([str(random.randint(0, 9)) for _ in range(15)])
        new_user.verify_key = verify_key
        new_user.is_active = False
        send_mail(
            subject='Подтверждение регистрации',
            message=f'Пройдите по ссылке для подтверждения регистрации на сайте SkyStore:\n'
                    f'http://127.0.0.1:8000/users/verify/{verify_key}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )
        return super().form_valid(form)


def verify_view(request, verify_key):
    for user in User.objects.all():
        if verify_key == user.verify_key:
            user.is_active = True
            user.save()
            return redirect(reverse('users:login'))

    return HttpResponse('Пользователь с такой почтой не регистрировался!')


class UserUpdateView(UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def user_password_recovery(request):
    context = {
        'title': 'Восстановление пароля'
    }
    users_set = User.objects.all()
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(15)])

    if request.method == 'POST':
        email = request.POST.get('email')
        # recovery_new_password(request, email=email)
        for user_ in users_set:
            if user_.email == email:
                send_mail(
                    subject='Восстановление пользователя',
                    message=f'Ваш новый пароль:\n'
                            f'{new_password}',
                    from_email=settings.EMAIL_HOST_USER,
                    recipient_list=[user_.email]
                )
                user_.set_password(new_password)
                user_.save()

    return render(request, 'users/user_password_recovery.html', context)


def recovery_new_password(request, email):
    users_set = User.objects.all()
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(15)])

    for user_ in users_set:
        if user_.email == email:
            send_mail(
                subject='Восстановление пользователя',
                message=f'Ваш новый пароль:\n'
                        f'{new_password}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[user_.email]
            )
            user_.set_password(new_password)
            user_.save()

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 align="center">Вход</h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Войти</button>
                <a href="{% url 'catalog:category_list' %}" class="btn">Отмена</a>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:user_password_recovery' %}" class="btn btn-danger">Не помню пароль</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3>Регистрация</h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Регистрация</button>
                <a href="{% url 'catalog:category_list' %}" class="btn">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row" enctype="multipart/form-data">
     <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Мой профиль
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Сохранить</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/user_password_recovery.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row text-start">
    <div class="col-3"></div>
    <div class="col-lg-6 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal"></h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <input type="text" name="email" class="form-control" id="name" placeholder="Введите email"
                               required>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}