blogs/urls.py
from django.urls import path

from blogs.apps import BlogsConfig
from blogs.views import BlogCreateView, BlogListView, BlogDetailView, BlogDeleteView, BlogUpdateView

app_name = BlogsConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('list/', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='blog_detail_view'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import contacts, CategoryCreateView, CategoryListView, ProductsListView, \
    CategoryUpdateView, CategoryDeleteView, ProductCreateView, ProductUpdateView, ProductDeleteView, ProductDetailView, \
    HomeView

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contacts/', contacts, name='contacts'),
    path('category/<int:pk>', ProductsListView.as_view(), name='category'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>', CategoryDeleteView.as_view(), name='category_delete'),
    path('category_list/', CategoryListView.as_view(), name='category_list'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('product/view/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_detail_view'),
    path('product/delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegistererView, verify_view, UserUpdateView, user_password_recovery

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('user_recovery/', user_password_recovery, name='user_password_recovery'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegistererView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('verify/<str:verify_key>', verify_view, name='verify'),
]

catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    title = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    image = models.ImageField(upload_to='catalog/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    purchase_price = models.IntegerField(verbose_name='Цена за покупку')
    date_of_creation = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    date_of_last_modification = models.DateField(auto_now=True, verbose_name='Дата последнего изменения')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Владелец')

    def __str__(self):
        return f'{self.title} ({self.category})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version_number = models.CharField(max_length=20, verbose_name='Номер версии')
    version_title = models.CharField(max_length=100, verbose_name='Название версии')
    current_version = models.BooleanField(verbose_name='Признак текущей версии', **NULLABLE)

    def __str__(self):
        return f'{self.version_number} / {self.version_title} ({self.product})'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version, Category


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        fields = ('title', 'description', 'category', 'image', 'purchase_price')

    def clean_title(self):
        cleaned_data = self.cleaned_data['title']

        for word in self.forbidden_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError(f'В продукте нельзя использовать слова: {", ".join(self.forbidden_words)}')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']

        for word in self.forbidden_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError(f'В продукте нельзя использовать слова: {", ".join(self.forbidden_words)}.')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'


class CategoryForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Category
        fields = ('title', 'description',)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, TemplateView

from catalog.forms import ProductForm, VersionForm, CategoryForm
from catalog.models import Product, Category, Version
from catalog.services import get_cached_categories


class HomeView(TemplateView):
    template_name = 'catalog/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        context_data['object_list'] = Product.objects.all().order_by('-date_of_last_modification')[:5]
        context_data['title'] = 'SkyStore - главная'
        context_data['product_versions'] = Version.objects.filter(product_id=self.kwargs.get('pk'))

        for object in context_data['object_list']:
            active_version = object.version_set.filter(current_version=True).first()
            if active_version:
                object.active_version_number = active_version.version_number
                object.active_version_title = active_version.version_title
            else:
                object.active_version_number = None
                object.active_version_title = None

        return context_data


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('catalog:category_list')


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('catalog:category_list')


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = Category
    success_url = reverse_lazy('catalog:category_list')


class CategoryListView(ListView):
    model = Category
    extra_context = {
        'title': 'Категории товаров'
    }

    def get_queryset(self):
        queryset = get_cached_categories()
        return queryset


class ProductsListView(ListView):
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['title'] = category_item.title
        context_data['product_versions'] = Version.objects.filter(product_id=self.kwargs.get('pk'))

        for object in context_data['object_list']:
            active_version = object.version_set.filter(current_version=True).first()
            if active_version:
                object.active_version_number = active_version.version_number
                object.active_version_title = active_version.version_title
            else:
                object.active_version_number = None
                object.active_version_title = None

        return context_data


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    extra_context = {
        'title': 'SkyStore',
    }


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:category', args=[self.object.category.pk])

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:category', args=[self.object.category.pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product

    def get_success_url(self):
        return reverse('catalog:category', args=[self.object.category.pk])


def contacts(request):
    context = {
        'title': 'Контакты'
    }
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'name: {name}\n'
              f'phone: {phone}\n'
              f'message: {message}\n')

    return render(request, 'catalog/contacts.html', context)

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h1 class="my-0 mr-md-auto font-weight-normal">Skystore</h1>
    <nav class="ms-5">
        <a class="p-2 btn btn-primary" href="{% url 'catalog:home' %}">Главная</a>
        <a class="p-2 btn btn-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        <a class="p-2 btn btn-primary" href="{% url 'catalog:category_list' %}">Категории</a>
        <a class="p-2 btn btn-primary" href="{% url 'blogs:blog_list' %}">Статьи</a>
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-success" href="{% url 'users:profile' %}">Профиль</a>
        <a class="p-2 btn btn-danger" href="{% url 'users:logout' %}">Выход</a>
        {% else %}
        <a class="p-2 btn btn-success" href="{% url 'users:login' %}">Вход</a>
        <a class="p-2 btn btn-success" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center ">
    <h1 class="display-4">{{title}}</h1>
</div>
<br><br>

<div class="container">

    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/category_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Удаление категории
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>
                    Вы точно хотите удалить категорию - {{object.title}}?
                </p>
                <button type="submit" class="btn btn-outline-danger">
                        Удалить
                </button>
                <a href="{% url 'catalog:category_list' %}" class="btn btn-outline-warning">Отмена</a>

            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/category_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                <h3>Редактирование категории</h3>
                {% else %}
                <h3>Создание категории</h3>
                {% endif %}
            </div>
            <div class="card-body">

                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                        Сохранить
                    {% else %}
                        Создать
                    {% endif %}
                </button>
                <a href="{% url 'catalog:category_list' %}" class="btn btn-outline-warning">Отмена</a>

            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<a href="{% url 'catalog:category_create' %}" type="button"
   class="btn btn-lg btn-outline-primary mb-5">Добавить категорию</a>
<div class="row text-center">
    {% for object in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h3 class="my-0 font-weight-normal">{{object.title}}</h3>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-3 text-start m-3">
                    <li>{{object.description|truncatechars:100}}</li>
                </ul>
            </div>
            <div class="card-footer">
                <a href="{% url 'catalog:category' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-primary mb-3">Перейти</a>
                <a href="{% url 'catalog:category_update' object.pk %}" type="button"
                   class="btn float-left">Изменить</a>
                <a href="{% url 'catalog:category_delete' object.pk %}" type="button"
                   class="btn float-right">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content %}
<h3>Последние 5 измененных товаров:</h3><br>
<div class="row text-center">
    {% for object in object_list %}
    {% include 'catalog/includes/inc_card_product.html' %}
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Удаление товара
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>
                    Вы точно хотите удалить товар - {{object.title}}?
                </p>
                <button type="submit" class="btn btn-outline-danger">
                        Удалить
                </button>
                <a href="{% url 'catalog:category_list' %}" class="btn btn-outline-warning">Отмена</a>

            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h3 class="my-0 font-weight-normal">{{object.title}}</h3>
                </div>
                <div class="card-body">
                    <h4 class="card-title pricing-card-title">Цена: {{object.purchase_price}} руб.</h4><br>
                    <h4 class="card-title pricing-card-title">Категория: {{object.category}}</h4><br>
                    <h4 class="card-title pricing-card-title">Описание:</h4>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{object.description}}</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
        <div class="col-6">
            <img src="{{ object.image|mymedia }}" class="img-fluid" alt="Card image cap">
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                <h3>Редактирование продукта</h3>
                {% else %}
                <h3>Создание продукта</h3>
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                        Сохранить
                    {% else %}
                        Создать
                    {% endif %}
                </button>
                <a href="{% url 'catalog:category_list' %}" class="btn btn-outline-warning">Отмена</a>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3>Версия</h3>
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% if not forloop.last %}
                        <hr>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<a href="{% url 'catalog:product_create' %}" type="button"
   class="btn btn-lg btn-outline-primary mb-5">Добавить товар</a>
<div class="row text-center">
    {% for object in object_list %}
    {% include 'catalog/includes/inc_card_product.html' %}
    {% endfor %}
</div>
{% endblock %}